### ISSUE TITLE
Js and css files missing

### ISSUE THREAD

**Issue by RjNayak** [davidctaylor/d3-react-tree#1]
Hi David,

The git project showing below files missing in the project
<script async src="dist/vendor.min.js"></script>
<script async src="dist/tree-menu-vendor.min.js"></script>
<script async src="dist/tree-menu.min.js"></script>
<link rel='stylesheet' href='stylesheets/main.css'/>
could you please suggest , from where I can include these files?

**Comment by davidctaylor** [comment]
Hi,

Those files are created as part of the build. Checkout the project and run the npm install and build commands

**Comment by RjNayak** [comment]
Thanks
